Add possibility to compute risk
JuliaStochOpt/StochDynamicProgramming.jl pull request #151
Opened 2017-07-21 09:35 UTC by Henri-Gerard

2017-07-27 12:16 UTC, leclere requested changes
It is a good first step. There are some naming problem to address : 
CVaR -> AVaR
beta should have the same understanding everywhere

It is also unclear if we are considering global risk measure or composed risk measure, and why the risk measures should be the same for each time step.

We also need an upper bound evaluation (which is not the expectation).

2017-07-27 12:16 UTC, leclere commented on examples/stock-example.jl
> +spmodel = LinearSPModel(N_STAGES,u_bounds,[S0],cost_t,dynamic,xi_laws, Expectation())
I think we should not have the last argument in this example

2017-07-27 12:16 UTC, leclere commented on src/StochDynamicProgramming.jl
> +        change_proba_risk,
why do we export this ?

2017-07-27 12:16 UTC, leclere commented on src/objects.jl
> +
We should add a polyhedral measure given as a collection of extreme points

2017-07-27 12:16 UTC, leclere commented on src/objects.jl
> +                           riskMeasure;
Should be optional, defaulting to Expectation.

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +Update probability distribution to consider only worst case scenarios
Unclear

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +Keep only the tail of the probability distribution given an order
unclear

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +    SDDP interface object
I don't understand

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +    erro("'change_proba_risk' not defined for $(typedof(s))")
erro or error ?

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +    real number
what is it ?

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +function change_proba_risk(prob,riskMeasure::CVaR,perm)
Change CVAR to AVAR everywhere.

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +Leave the probability distribution unchanged to calculate the expectation.
compute

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +function change_proba_risk(prob, riskMeasure::RiskMeasure,perm)
We should find another name for this function.

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +Update the probability distribution to calculate a convex combination
compute

2017-07-27 12:16 UTC, leclere commented on src/risk.jl
> +    beta = 1-riskMeasure.beta
dangerous

2017-07-27 12:16 UTC, leclere commented on src/stopcrit.jl
> +type Stabilization <: AbstractStoppingCriterion
change to LBStabilization

2017-07-27 12:16 UTC, leclere commented on test/changeprob.jl
> +    for i in 0:10
might be a lot of testing of the same feature ?

2017-07-27 12:16 UTC, leclere commented on test/changeprob.jl
> +@testset "Equality formulations" begin
comment a bit the test

2017-07-27 12:16 UTC, leclere commented on test/extensive_formulation.jl
> +                                                        x0, cost, dynamic, laws, Expectation())
use default value

2017-07-27 12:16 UTC, leclere commented on test/sddp.jl
> +                                                  x0, cost, dynamic, laws, Expectation())
use default value

2017-07-27 12:16 UTC, leclere commented on test/sddp.jl
> +                                                      x0, cost, dynamic, laws, Expectation(),
use default value

2017-07-27 12:16 UTC, leclere commented on test/sddp.jl
> +                                                      dynamic, laws, Expectation())
use default value

2017-07-27 12:16 UTC, leclere commented on test/sddp.jl
> +                                                      Expectation(),
use default value

2017-07-27 12:16 UTC, leclere commented on test/sddp.jl
> +                                                      dynamic, laws, Expectation())
use default value

2017-07-27 12:16 UTC, leclere commented on test/sdp.jl
> +            dynamic, aleas, Expectation())
use default value

2017-07-27 12:16 UTC, leclere commented on test/sdp.jl
> +                                                                   dynamic, aleas, Expectation())
use default value

2017-07-27 12:16 UTC, leclere commented on src/objects.jl
> +    # level of risk aversity (0 = Expectation, 1 = Worst Case):
Give the definition

2017-07-27 12:16 UTC, leclere commented on src/objects.jl
> +    # level of risk aversity (0 = Expectation, 1 = Worst Case):
give the definition

2017-07-28 07:08 UTC, odow commented
> We also need an upper bound evaluation (which is not the expectation).

How should one do this? At one point I implemented a bootstrapping method which ran a whole heap of monte-carlo simulations, then sampled a subset of those objective values (with replacement) to calculate a confidence interval for the risk-adjusted objective.

2017-08-31 14:15 UTC, Henri-Gerard commented on src/StochDynamicProgramming.jl
> +        change_proba_risk,
If people want to compute risk afterwards on some particular costs to compare evaluation, it could be useful

2017-11-03 10:09 UTC, frapac approved these changes
I think we should close this PR ASAP?

2017-11-03 10:09 UTC, frapac commented on examples/risk-example.jl
> +println("Initialzing functions to compare execution time")
Typo!

2017-11-03 10:09 UTC, frapac commented on src/forwardBackwardIterations.jl
> +        proba = argsup_proba_risk(proba,model.riskMeasure,costs)
I think we should note replace the proba inplace. Rather set:
`riskproba = ... `

Could we made the name of the function more explicit?

2017-11-03 10:09 UTC, frapac commented on src/objects.jl
> +
Maybe add a docstring here?

2017-11-03 10:09 UTC, frapac commented on src/risk.jl
> +function argsup_proba_risk(prob,riskMeasure::AVaR,costs)
Maybe it would be a better idea to modify the `prob` vector inplace.

2017-11-03 10:09 UTC, frapac commented on src/stopcrit.jl
> +end
:+1:

2017-11-03 12:20 UTC, merged