New bounds
JuliaStochOpt/StochDynamicProgramming.jl pull request #156
Opened 2017-08-03 15:08 UTC by leclere

* allow varying time bound constraint, working in sddp, deteriorated in sdp
* adapt examples and improve comments
* added subgradient recovering function

2017-08-03 15:09 UTC, leclere commented
At the moment the Cut Pruning and integer are not working.

2017-08-04 14:15 UTC, frapac requested changes
I am working on fixing the cut selection algorithm

2017-08-04 14:15 UTC, frapac commented on examples/stock-example.jl
> +    return COSTS[t]* u[1] #
Can we remove the trailing # ?

2017-08-04 14:15 UTC, frapac commented on src/SDDPoptimize.jl
> +function get_lower_bound(sddp::SDDPInterface)
Why build a function similar as `lowerbound` ?

2017-08-04 14:15 UTC, frapac commented on src/SDDPoptimize.jl
> +return Vt.lambdas[index, :]
Indentation

2017-08-04 14:15 UTC, frapac commented on src/objects.jl
> +function iswithinbounds(x, bounds::Array)
This function can be optimized (break for loop if test became negative)

2017-08-04 14:15 UTC, frapac commented on src/oneStepOneAleaProblem.jl
> +     end
This is a major slow down in the algorithm: the fact that we need to redefine the objective each time we call `one_step_one_alea` in any configuration is too much an overhead IMO. 

My benchmark shows that the performance decreases in `new_bounds`, compared to `master`: the execution time increases from 8s to 17s ...

2017-08-04 14:15 UTC, frapac commented on src/oneStepOneAleaProblem.jl
> +        #error("Foo")
Can we remove the commented lines?

2017-08-04 14:15 UTC, frapac commented on src/sdp.jl
> +        cons_fun(t,x,u,w) = true
Trailing whitespace :)

2017-08-07 06:56 UTC, trigaut commented on src/sdp.jl
> +        cons_fun(t,x,u,w) = true
I have to reconfigure sublime sorry ;)

2017-08-23 15:21 UTC, frapac commented
I fix the problem with cuts pruning. 

Otherwise, I confirm that QP regularization works, but SMIP is broken ...

2018-05-21 15:54 UTC, closed without merging